package conventionhub.pojos;
// Generated Jul 30, 2020, 1:16:07 PM by Hibernate Tools 4.3.1



/**
 * ChitietHoinghi generated by hbm2java
 */
public class ChitietHoinghi  implements java.io.Serializable {


     private int maHn;
     private Hoinghi hoinghi;
     private String motaChiTiet;

    public ChitietHoinghi() {
    }

    public ChitietHoinghi(Hoinghi hoinghi, String motaChiTiet) {
       this.hoinghi = hoinghi;
       this.motaChiTiet = motaChiTiet;
    }
   
    public int getMaHn() {
        return this.maHn;
    }
    
    public void setMaHn(int maHn) {
        this.maHn = maHn;
    }
    public Hoinghi getHoinghi() {
        return this.hoinghi;
    }
    
    public void setHoinghi(Hoinghi hoinghi) {
        this.hoinghi = hoinghi;
    }
    public String getMotaChiTiet() {
        return this.motaChiTiet;
    }
    
    public void setMotaChiTiet(String motaChiTiet) {
        this.motaChiTiet = motaChiTiet;
    }




}


