package conventionhub.pojos;
// Generated Jul 30, 2020, 1:16:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Dangkyhoinghi generated by hbm2java
 */
public class Dangkyhoinghi  implements java.io.Serializable {


     private DangkyhoinghiId id;
     private Hoinghi hoinghi;
     private User user;
     private boolean daDuocDuyet;
     private Date createdDate;

    public Dangkyhoinghi() {
    }

    public Dangkyhoinghi(DangkyhoinghiId id, Hoinghi hoinghi, User user, boolean daDuocDuyet, Date createdDate) {
       this.id = id;
       this.hoinghi = hoinghi;
       this.user = user;
       this.daDuocDuyet = daDuocDuyet;
       this.createdDate = createdDate;
    }
   
    public DangkyhoinghiId getId() {
        return this.id;
    }
    
    public void setId(DangkyhoinghiId id) {
        this.id = id;
    }
    public Hoinghi getHoinghi() {
        return this.hoinghi;
    }
    
    public void setHoinghi(Hoinghi hoinghi) {
        this.hoinghi = hoinghi;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public boolean isDaDuocDuyet() {
        return this.daDuocDuyet;
    }
    
    public void setDaDuocDuyet(boolean daDuocDuyet) {
        this.daDuocDuyet = daDuocDuyet;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


