package conventionhub.pojos;
// Generated Jul 30, 2020, 1:16:07 PM by Hibernate Tools 4.3.1



/**
 * DangkyhoinghiId generated by hbm2java
 */
public class DangkyhoinghiId  implements java.io.Serializable {


     private int user;
     private int hoinghidangky;

    public DangkyhoinghiId() {
    }

    public DangkyhoinghiId(int user, int hoinghidangky) {
       this.user = user;
       this.hoinghidangky = hoinghidangky;
    }
   
    public int getUser() {
        return this.user;
    }
    
    public void setUser(int user) {
        this.user = user;
    }
    public int getHoinghidangky() {
        return this.hoinghidangky;
    }
    
    public void setHoinghidangky(int hoinghidangky) {
        this.hoinghidangky = hoinghidangky;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DangkyhoinghiId) ) return false;
		 DangkyhoinghiId castOther = ( DangkyhoinghiId ) other; 
         
		 return (this.getUser()==castOther.getUser())
 && (this.getHoinghidangky()==castOther.getHoinghidangky());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUser();
         result = 37 * result + this.getHoinghidangky();
         return result;
   }   


}


