package conventionhub.pojos;
// Generated Jul 30, 2020, 1:16:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TinhtrangxoaDiadiem generated by hbm2java
 */
public class TinhtrangxoaDiadiem  implements java.io.Serializable {


     private int madiadiem;
     private Diadiem diadiem;
     private boolean tinhtrangxoa;
     private Date createdDate;
     private Date latestModified;

    public TinhtrangxoaDiadiem() {
    }

    public TinhtrangxoaDiadiem(Diadiem diadiem, boolean tinhtrangxoa, Date createdDate, Date latestModified) {
       this.diadiem = diadiem;
       this.tinhtrangxoa = tinhtrangxoa;
       this.createdDate = createdDate;
       this.latestModified = latestModified;
    }
   
    public int getMadiadiem() {
        return this.madiadiem;
    }
    
    public void setMadiadiem(int madiadiem) {
        this.madiadiem = madiadiem;
    }
    public Diadiem getDiadiem() {
        return this.diadiem;
    }
    
    public void setDiadiem(Diadiem diadiem) {
        this.diadiem = diadiem;
    }
    public boolean isTinhtrangxoa() {
        return this.tinhtrangxoa;
    }
    
    public void setTinhtrangxoa(boolean tinhtrangxoa) {
        this.tinhtrangxoa = tinhtrangxoa;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getLatestModified() {
        return this.latestModified;
    }
    
    public void setLatestModified(Date latestModified) {
        this.latestModified = latestModified;
    }




}


