package conventionhub.pojos;
// Generated Jul 30, 2020, 1:16:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TinhtrangxoaHoinghi generated by hbm2java
 */
public class TinhtrangxoaHoinghi  implements java.io.Serializable {


     private int idtinhtrangxoaHoinghi;
     private Hoinghi hoinghi;
     private boolean tinhtrangxoa;
     private Date latestModified;
     private Date createdDate;

    public TinhtrangxoaHoinghi() {
    }

    public TinhtrangxoaHoinghi(Hoinghi hoinghi, boolean tinhtrangxoa, Date latestModified, Date createdDate) {
       this.hoinghi = hoinghi;
       this.tinhtrangxoa = tinhtrangxoa;
       this.latestModified = latestModified;
       this.createdDate = createdDate;
    }
   
    public int getIdtinhtrangxoaHoinghi() {
        return this.idtinhtrangxoaHoinghi;
    }
    
    public void setIdtinhtrangxoaHoinghi(int idtinhtrangxoaHoinghi) {
        this.idtinhtrangxoaHoinghi = idtinhtrangxoaHoinghi;
    }
    public Hoinghi getHoinghi() {
        return this.hoinghi;
    }
    
    public void setHoinghi(Hoinghi hoinghi) {
        this.hoinghi = hoinghi;
    }
    public boolean isTinhtrangxoa() {
        return this.tinhtrangxoa;
    }
    
    public void setTinhtrangxoa(boolean tinhtrangxoa) {
        this.tinhtrangxoa = tinhtrangxoa;
    }
    public Date getLatestModified() {
        return this.latestModified;
    }
    
    public void setLatestModified(Date latestModified) {
        this.latestModified = latestModified;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


