package conventionhub.pojos;
// Generated Jul 30, 2020, 1:16:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.BooleanProperty;
import javafx.beans.property.SimpleBooleanProperty;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private String ten;
     private String username;
     private String password;
     private String email;
     private boolean tinhTrangBlock;
     private Date createdDate;
     private Date latestModified;
     private boolean isAdmin;
     private Set<Dangkyhoinghi> dangkyhoinghis = new HashSet<Dangkyhoinghi>(0);

     private BooleanProperty tinhtrangblockBooleanProperty;
     public BooleanProperty tinhtrangblockProperty(){
         if(tinhtrangblockBooleanProperty == null) tinhtrangblockBooleanProperty = new SimpleBooleanProperty();
         return tinhtrangblockBooleanProperty;
     }
     
    public User() {
    }

	
    public User(String username, String password, String email, boolean tinhTrangBlock, Date createdDate, Date latestModified, boolean isAdmin) {
        this.username = username;
        this.password = password;
        this.email = email;
        this.tinhTrangBlock = tinhTrangBlock;
        this.createdDate = createdDate;
        this.latestModified = latestModified;
        this.isAdmin = isAdmin;
    }
    public User(String ten, String username, String password, String email, boolean tinhTrangBlock, Date createdDate, Date latestModified, boolean isAdmin, Set<Dangkyhoinghi> dangkyhoinghis) {
       this.ten = ten;
       this.username = username;
       this.password = password;
       this.email = email;
       this.tinhTrangBlock = tinhTrangBlock;
       this.createdDate = createdDate;
       this.latestModified = latestModified;
       this.isAdmin = isAdmin;
       this.dangkyhoinghis = dangkyhoinghis;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isTinhTrangBlock() {
        return this.tinhTrangBlock;
    }
    
    public void setTinhTrangBlock(boolean tinhTrangBlock) {
        this.tinhTrangBlock = tinhTrangBlock;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getLatestModified() {
        return this.latestModified;
    }
    
    public void setLatestModified(Date latestModified) {
        this.latestModified = latestModified;
    }
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public Set<Dangkyhoinghi> getDangkyhoinghis() {
        return this.dangkyhoinghis;
    }
    
    public void setDangkyhoinghis(Set<Dangkyhoinghi> dangkyhoinghis) {
        this.dangkyhoinghis = dangkyhoinghis;
    }




}


